---
format: 
  docx:
    reference-doc: my_styles.docx
title: "Addressing climate change and development pressures in an urban estuary through habitat restoration planning"
shorttitle: "Tampa Bay watershed habitat restoration planning"
bibliography: refs.bib
csl: frontiers-in-ecology-and-evolution.csl
author: 
  - Gary E Raulerson:
      email: gmangrove@gmail.com
      institute: [TBEP]
      correspondence: false
  - Douglas E Robison:
      email: DRobison@esassoc.com 
      institute: [ESA]
      correspondence: false
  - Marcus W Beck:
      email: mbeck@tbep.org
      institute: [TBEP]
      correspondence: true
  - Maya C Burke:
      email: mburke@tbep.org
      institute: [TBEP]
      corrspondence: false
  - Justin Saarinen:
      email: justinsaarinen@gmail.com 
      institute: [ESA]
      correspondence: false
  - Christine Sciarrino:
      email: CSciarrino@esassoc.com 
      institute: [ESA]
      correspondence: false
  - Edward T Sherwood:
      email: esherwood@tbep.org 
      institute: [TBEP]
      correspondence: false
  - David A Tomasko:
      email: dave@sarasotabay.org
      institute: [SBEP]
      correspondence: false
institute:
  - TBEP: Tampa Bay Estuary Program, St. Petersburg, Florida 33701 USA
  - ESA: Environmental Science Associates, Tampa, Florida 33609 USA
  - SBEP: Sarasota Bay Estuary Program, Sarasota, Florida 34236 USA

filters: 
  - templates/scholarly-metadata.lua
  - templates/author-info-blocks.lua
---

## Abstract

Native habitats in Florida face dual pressures at the land-sea interface from urban development and sea-level rise associated with climate change. To address these pressures, restoration practitioners require robust tools that identify reasonable goals given historical land use trends, current status of the habitat mosaic, and anticipated future impacts from coastal stressors. A target-setting approach for native habitats was created for the Tampa Bay watershed that identifies current restoration opportunities and establishes short (2030) and long-term (2050) goals. The approach was informed through a three-decade habitat change analysis and over forty years of habitat restoration experience in the region. Restoration goals were defined based on what is possible today and the projected needs for the future, rather than attempting to replicate past ecological conditions. The new paradigm also accounts for the expected impacts of sea-level rise, climate change, and watershed development - stressors which are pervasive in Florida. The resulting habitat goals are spatially explicit with maps that identify remaining restoration and conservation opportunities, while also providing an approach for the entire watershed that targets subtidal, intertidal, and coastal uplands. This approach represents a general framework to support coastal planning decisions that need to address competing interests and could be applied in other coastal settings where sustainable urbanization practices need to co-exist with natural environments. Methods for repeatable analyses are also available using an open source workflow to update progress over time and for adoption by others.

## Introduction

The health of estuarine systems, coastal habitats, and associated fauna and flora are inextricably linked to land uses and management throughout the watershed [@Yoskowitz15] These habitats provide multiple ecosystem services, including wildlife shelter and migratory corridors [@Yoskowitz15], fisheries production [@Houde93], water quality improvement [@Kushlan90; @Sprandel00; @AvilaGarcia20], erosion and flood attenuation [@Calil15; @Menendez18], carbon sequestration [@Dontis20] and recreation [@Chung18]. The Tampa Bay Estuary Program (TBEP) is one of 28 programs administered by the US Environmental Protection Agency (USEPA) under the National Estuary Program (NEP). In recognition of threats to habitats from development and climate change stressors, the TBEP and partners recently created the third iteration of a plan to establish targets and goals for habitat restoration within the Tampa Bay watershed. As an NEP, the program has guided regional environmental restoration initiatives for the estuary since 1991. The methodologies used in the creation of a 2020 Habitat Master Plan Update for Tampa Bay [@Robison20] are highly transferable to both coastal and non-coastal systems.

## Development, climate change, and coastal squeeze 

Development causes multiple perturbations within any watershed. The accumulated impacts of construction and associated infrastructure remove or substantially modify existing habitats, and can alter hydrology of nearby streams and rivers [@Theobald97; @Sim14]. Given the degree to which the Tampa Bay watershed has been urbanized, the synergistic effects of continued coastal development and future climate change are primary concerns for maintenance of estuarine and coastal habitat health. Observed and potential adverse effects of climate change and sea level rise on marine and estuarine ecosystems are well-documented [@Scavia02; @Spalding07; @Titus09]. With regard to estuarine habitats, the primary concerns are that sea level rise is now occurring at such a rapid rate that the landward migration of tidal wetlands in response cannot keep pace; or that the upland slope has already been lost to urban development and hardening, leaving no place for tidal wetland migration [@Titus09]. Geological, physical and chemical changes could include alterations in sediment deposition and erosion patterns, micro-topography, and water quality [@Arnell15; @Whitehead09].

Related changes in habitats in response to climate change (sea level rise and warming) include landward migration of mangroves into salt marshes, upstream migration of salt marshes within tidal tributaries, and upland forest migration [@Brinson95; @Vogelmann12; @Cavanaugh19]. Species dependent upon these habitats will be forced to change use patterns or adapt to the new conditions [@Iwamura13]. For example, while black needle rush (*Juncus roemerianus*) can tolerate a wide salinity range [@Eleuterius79; @Stout84], the largest remaining *J. roemerianus* marshes in Tampa Bay are located in the lower-salinity reaches of tidal rivers and creeks. The greatest extents of those marshes occur in river systems where their upstream extent is constrained by impoundments for public water supplies. Spatial restriction in these hydrologically truncated rivers may make these marshes particularly vulnerable to "pinching out", as upstream migration in response to sea level rise will be cut off by anthropogenic barriers. Similarly, landward migration of salt barrens (high marsh areas in Tampa Bay) in response to sea level rise will be restricted by the filling and hardening of coastal uplands associated with existing or future urban development.

## Need for a paradigm shift 

The synergistic effects of development and climate change diminish the available space for future restoration in urbanizing estuaries, thereby impacting the variety of ecosystem services provided by these habitats and the wildlife they support [@Enwright15]. Given projected habitat losses without intervention efforts and the limited resources (including time, land, funding, and labor force) available, it is important to appropriately and realistically site restoration projects to increase the likelihood of success. To achieve this objective, a new restoration approach on a broad watershed scale will be implemented.

Previously, a "retrospective" approach to setting habitat protection and restoration targets in Tampa Bay was employed [@Lewis96; @Robison10; @Cicchetti11; @Russell15]. Under this paradigm, priority was given to restoration activities focused on habitat types, important for a suite of ten estuarine faunal guilds, that were disproportionately lost or degraded compared to a benchmark period. Primary criticisms of this approach included a lack of consideration for future sea level rise and other climate change factors [@Yoskowitz15], use of expanded and different habitats outside the Tampa Bay watershed by the faunal guilds [@Robison10], lack of attention to upland or freshwater wetland habitats, and little recognition of other stressors such as land development trends or actual available space for restoration efforts.

Past approaches for guiding restoration planning have been successfully used in other contexts, but they do not fully balance competing needs. For example, an integrated watershed approach [@EPA96] has been utilized since the early 1990s to diagnose and manage water quantity and quality problems that have contributed to seagrass restoration in the system. Additionally, the habitat mosaic approach [@Henningsen05] of including multiple habitat types within restoration projects is recognized as necessary in Tampa Bay [@Hughes11] and elsewhere to allow for ecosystem state changes in response to different environmental pressures [@Duarte09; @Palmer09].

Adaptive management [@Holling78; @Gregory06] components have been increasingly used to address challenges of sea level rise, climate change, and development stressors, including monitoring to identify critical restoration decision points and needed intervention with contingency plans. Rising sea levels and temperatures and altered rainfall patterns are causing observable changes to habitats on a global scale [@Cavanaugh14; @Garner15; @Yoskowitz15], including within Tampa Bay [@Price17], and those changes are expected to become more pronounced over the next several decades [@Sheehan16; @Nerem18].

## Updating the approach

The new approach integrates the whole watershed, addresses historical changes, focuses on trajectories that have occurred during more contemporary time periods, and considers both current and future stressors -- particularly land development and sea level rise. There is relatively consistent extent and distribution data for most Tampa Bay habitats of interest (1988 to 2018), representing a time period when federal, state and local regulations were in effect and regional impacts from climate change are documented [@Raabe12; @Cavanaugh14]. This approach establishes a broader framework that guides both watershed-level habitat master planning and site-level restoration design activities and incorporates applicable elements of the other habitat restoration paradigms discussed above [@Palmer09]. Our broader framework for guiding restoration activities includes 1) designation of habitat types by strata relative to the aquatic-terrestrial gradient, 2) quantification of historical trends by habitat types to identify appropriate future targets in acreage, and 3) identification of opportunity areas that could be used by practitioners to achieve restoration goals based on habitat type and past trajectories.

With regard to habitat restoration projects, the design approach must envision not only what is possible today, but also what the coastal landscape will look like in 50 years and beyond. Design features should continue to use the historical "habitat mosaic" approach, but should also include coastal upland features that accommodate tidal inundation and the landward advance of emergent tidal wetlands [@Enwright16].

## References
