---
format: 
  docx:
    reference-doc: my_styles.docx
    number-sections: false
bibliography: ../refs.bib
csl: ../frontiers-in-ecology-and-evolution.csl
---

We sincerely thank the reviewers for providing comments on our manuscript.  We provide a point-by-point response to these comments below.   

All page and line numbers in the reviewer comments refer to the original submission.  Page numbers noted in our response refer to the revised submission.

## Reviewer 2 

The authors suggest an interesting planning tool for coastal restoration. However, in the case given by the author, the basis for judging whether wetlands can be restored is very subjective, and there is no actual data to support whether such judgment is real and feasible, which is the biggest problem of the paper.

* __Response__: Thank you for your comments on the draft manuscript.  We have made every effort to provide responses to your concerns and have revised the text as needed, particularly for use of our approach to identify actual restoration potential (see response to your comments on lines 304-316). We are confident these changes have addressed your concerns and strengthened the content therein.  

Line 76. How to determine the benchmark period, or what is the benchmark period in the study area, decades ago?

* __Response__: Apologies for the omission of that critical detail.  The benchmark period is defined as circa 1950 when the earliest historical aerial photographs of Tampa Bay and its watershed were available.  This time period is defined as pre-development in @Robison10 and the citations that precede the sentence.  

    The text was amended as follows: "Priority was given to restoration activities focused on habitat types that were important for a suite of estuarine faunal guilds disproportionately lost or degraded compared to a circa 1950 benchmark period considered as pre-development."

Line 127-128. 5-foot contour is the absolute elevation or elevation relative to sea level?

* __Response__: The explicit definition of the 5-foot contour was previously provided on lines 211-213 as the area of land from the local Mean Lower Low Water elevation extending landward to the elevation 5 feet above Mean Sea Level. The definition was moved to this section for clarity.    

Line 140. What are the specific contents of short-term and long-term goals? The reader may want a comparison table of the two goals

* __Response__: The identified short-term targets and long-term goals are provided in Table 5 and they are not presented at this point in the text because the methods that follow describe the process by which they were identified.  

     However, we have added some text to provide some clarity on on these terms: "The short-term targets provided an interim set of native habitat coverages to attain within a reasonable planning horizon, after which progress in attaining the long-term goals will be re-assessed."

Line 206-215. The actual available space for restoration efforts depends on the relative relation between wetland elevation and tide height. Whether the slope or elevation of coastal wetlands is used to estimate the potential restoration area under the impact of sea level rise. The author should give specific elevation data and tidal data.

* __Response__: We assume that this comment relates to your general concern that our approach does not provide an explicit quantification of the actual restoration potential of wetlands, either tidal or freshwater.  We certainly agree that identification of wetland restoration areas requires a more detailed assessment of land characteristics, including but not limited to elevation and slope data.  The approach described herein is primarily a screening and prioritization tool that requires additional work for on-site restoration planning. We hope that our response to your comments on lines 304-316 below addresses this concern.

Line 216-220 and Figue2. In addition to the land use/land cover data, I think it is important to consider the digital elevation data as well as the relative sea level rise data.

* __Response__: Please see the response to the previous comment and below regarding comments to lines 304-316. 

Line 236. What is the classification standard of xeric, mesic, or hydric soil? Due to sea level rise, wetland soil salinity changes, resulting in the transformation of the spatial pattern of freshwater wetland to saltwater wetland, how to consider this.

* __Response__: As noted in the manuscript, these classifications are defined in @Ries14, but historically are defined in @Baldwin38.  The latter citation was added. Additionally, we certainly agree that soil types may change over time as affected by sea level rise.  However, the coastal stratum included in the 5-foot contour considers the likely rate of sea level rise [sensu @Burke19] within the 2030 and 2050 time period used to establish the targets and goals.  That is, the coastal stratum provides a distinction for the restoration potential of wetlands (mesic/hydric soils) as tidal within the five foot contour (mangroves, salt barrens, salt marshes) and freshwater above the five foot contour (forested and non-forested wetlands) within the expected time period of sea level rise.  

     We have added some text at the end of the paragraph to make this clear: "This distinction explicitly accounts for potential salinity changes to soil properties as a function of sea-level rise based on regional projections in the time period for establishing the targets and goals."

Line 248-249. The author needs to specify which data analysis methods were used?

* __Response__: The analysis methods are the set of spatial operations described in the preceding text in the same section and as outlined in Figure 2.  The sentence was revised to make this more clear.  We have also noted two core geospatial functions that were used, as examples, in the text that followed. Readers can view the linked repository for specific details as needed.  

Line 304-316. The determination of potential repair area lacks quantitative basis. The priority of potential restoration areas at different locations depends on substrate conditions, ecological importance, engineering implementation, and restoration costs. For the whole region, the restoration potential of various ecosystems should be ranked, and only when they exceed a certain threshold can they be judged as having the operability and real potential of restoration under realistic conditions. Current opportunity maps simply overlap land use type data and soil data. I think such judgment is too subjective and arbitrary, lack of quantitative basis. Since the author mentions that there are data on restoration projects, why not use the projects already carried out to determine whether these potential restoration areas can actually be repaired in the future?

* __Response__: We certainly appreciate the concerns that our approach does not provide a more comprehensive quantitative means of identifying actual restoration potential.  Additional information, as noted by the reviewer, is certainly needed for understanding the true restoration potential of any location within the watershed.  However, we have noted in several locations in the manuscript that the approach described herein is a prioritization tool that can be used as a first step for restoration planning (e.g., lines 83, 90, 113).  Prior to this assessment, comparable tools at the watershed scale were not available and we believe that our approach is valuable in identifying potential restoration areas that regional managers could leverage for planning purposes.  In fact, our use of the term restoration "potential" was meant to describe this tool as a preliminary means to guide follow-up work once sites are identified from the provided opportunity areas.  

     That being said, it is worth further clarifying the intent of our approach as a prioritization tool that warrants additional work should restoration projects be pursued at the locations identified by our spatial analyses.  We have added text to two key locations to make this clear.  

     First, the following was added to the introduction on line 96: "These opportunity areas provide a first assessment of where restoration could occur, where on the ground assessments could be pursued to further quantify restoration potential."  

     Second, the following was added to the methods on line 197: "The identification of these areas on a broad spatial scale serves as a planning tool for restoration practitioners, where follow-up assessments are expected to more fully quantify restoration potential at selected sites."
"
Figure 1. The classification criteria for land use types are confused. I suggest using the Ramsar Convention classification system.

* __Response__: The classification criteria used in the figure was based on the FLUCCS approach described in the text (lines 157), with some categories combined for clarity in the figure. For example, "urban/open lands" includes 13 FLUCCS categories considered relevant for combining and displaying together in the map as a single category to show the extent of development in the Tampa Bay watershed.  The figure caption was revised to describe this approach. An additional citation to @Kawula18 was also added in the text and figure caption. This classification was chosen as this is the standard approach used for the entire state of Florida.  

## Reviewer 3

This paper presents a detailed method for spatial restoration planning using available landcover datasets for the Tampa Bay watershed. The authors provide a concise overview of the approach with the intention that the method can be applied in other regions. The research is important and relevant given the challenges related to both increasing development while considering conservation targets under potential climate change are widespread.

Overall, the paper is well-written and the authors provide a clear justification of the method, including the strengths (open source workflow), and limitations (detailed inputs, potential lag between reported restoration actions and observed landcover change in GIS products). Detailed comments on each section are provided below. Line numbers refer to those on the PDF version available for review.

* __Response__: Thank you for your detailed comments on our manuscript.  We have made every effort to address your concerns noted below and are confident this has improved the draft. 

Abstract:

While the paper is focused on the method and spatial classification to identify areas for potential restoration, this is not represented in the Abstract. Instead, the Abstract indicates a focus on the target-setting approach and emphasizes how sea-level rise, climate change, and watershed development are incorporated into this approach. The Abstract should rather focus on the main results of the paper – which was the identification of the different areas and changes over time as measured by applying the method. That is not to say that the entire Abstract is unsuitable, rather that it needs to be amended to better reflect the contents of the paper, rather than a summary of the approach.

* __Response__: 

Introduction:

The Introduction would benefit from a stronger rationale / context in the opening paragraph. This first paragraph intends to highlight the ecological importance of estuarine / coastal ecosystems by listing ecosystem services and then mentioning impacts from anthropogenic activities and climate change. The rationale is focused on the need for management to incorporate stressors using a socio-ecological systems approach (L41-43). While this rationale is valid, the sentences leading up to it are somewhat disjointed. The readability could be improved by considering the information in the first and second paragraph together and then restructuring to provide better context. For example, L39-43 “Habitat changes in response to climate change include landward migration of mangroves into salt marshes, upstream migration of salt marshes within tidal tributaries, and upland forest migration” is a very limited description, with no prior reference to the process of landward migration. A more descriptive narrative to the opening paragraphs of the Introduction will set the tone for the paper and further support the relevance and importance of the work.

* __Response__: 

Methods:

L107: Should this read as “altered the natural habitats of”

* __Response__: Corrected.

L117-126: If possible, it would help to have this information on the habitat layers and respective source material presented in a table – even as supplementary information.

* __Response__: Text was added to refer the reader to a new supplement Table S1. 

L127: At first mention of the 5-foot contour please provide an estimate in metres for comparison. This will also make for a more straightforward understanding of the SLR projection, which is provided in cm (L132).

* __Response__: This sentence was revised as follows "...location relative to the 5-foot contour (~1.5m elevation) that covers an area of land...".

L130-132: The SLR trend and projections to 2100 are stated here, but it is not clear whether these have been incorporated into the 2030 / 2050 targets / goals for restoration. In the Introduction (L83-86), it is stated that the approach will consider future stressors, including SLR. A spatial representation of how habitat / land cover may change by 2030 / 2050 under SLR is however not part of the Results. Were the SLR projections incorporated spatially? And did this impact the potential restoration areas? For example, are transitions from mangrove to tidal flat / seagrass included in the targets / goals when considering SLR? Please provide some additional information on whether this was incorporated and how it was done. This is needed to justify the statement in L83-86.

* __Response__: 

L154-165: Please indicate the type and scale of the spatial datasets for the habitat. Are these raster datasets? What is the grid resolution? Are they obtained from Landsat, or other remotely-sensed products? Providing detail on the input datasets will greatly assist any effort to replicate this method in another region.

* __Response__: Both the subtidal and inter/supratidal data layers are vector products produced by photo-interpretation.  Details were added as follows. 

     For the subtidal layers, details were added starting on line 150: "These data include vector polygons coverages of the major subtidal habitat types in Tampa Bay, as interpreted from 1:24,000 scale natural color aerial photographs flown in winter 2018 under cloud free conditions.  Accuracy assessments of the photo-interpreted map product included field verification by random sample points, with a requirement of 90% accuracy for the seagrass categories.  The minimum mapping unit for seagrass polygons is reported as 0.25 acres."
     
     For the inter/supratidal layers, details were added on line 158: "Similar methods as the subtidal habitats described above are used for the intertidal and supratidal coverage maps, although at a slightly higher spatial resolution (1:12,000)."

L170-175: Please provide more detail on how the habitat coverage change analysis was performed. Was this a simple calculation of total area change per habitat type derived from pixel count / polygon area? Or, were the maps for different years overlayed and a spatial algorithm applied to calculate differences? Please specify how the change from one habitat to another was estimated in order to generate the alluvial diagrams.

* __Response__: Additional detail was provided as follows: "Specifically, the spatial datasets were unioned and the total areal change of the polygons for each habitat type was quantified by taking the difference between the two terminal years.  For example, the area that remained as native uplands between the 1990 and 2017 intertidal and suptratidal layers was quantified, whereas the area that changed from native uplands to another habitat category was also quantified.  This process was repeated for all native habitats, including developed and restorable lands (described below)."

L177-188: While I understand the justification to differentiate between “restoration” and “enhancement” activities, I would suggest the authors re-consider the terminology and definitions they have provided. The term “restoration” is well-known, with the definition provided by the Society of Ecological Restoration becoming mainstreamed, particularly under the “Decade for Ecosystem Restoration”. The SER definition for restoration from the international principles and standards (https://www.ser.org/page/SERStandards): “the process of assisting the recovery of an ecosystem that has been degraded, damaged or destroyed. (Ecosystem restoration is sometimes used interchangeably with ecological restoration, but ecological restoration always addresses biodiversity conservation and ecological integrity, whereas some approaches to ecosystem restoration may focus solely on the delivery of ecosystem services.)” Therefore, it is advised that the authors do not provide their own definition for restoration to only refer to activities where earthwork is involved to reshape the land. Rather, it would be better to state what type of restoration activity has been conducted, instead of using the holistic / encompassing term “restoration” to only refer to a specific subset of activities. Given the definition provided by the authors, it needs to be clarified if all areas indicated as “potential restorable’ would therefore require earthwork in order to revert to natural habitat? Or in this case does “restorable” encompass the greater suite of possible activities?

* __Response__: 

L206-207 and Table1: Is there a difference in using the term “reservation” when referring to the coastal areas, vs. the term “conservation” being used for the upland areas? Looking at Table 4, there are coastal habitats in conservation areas. Is this to just designate specifically areas that are within the 5ft contour, regardless of protection status – this was my understanding from Table 1, but it would be beneficial to have it stated more clearly in the text.

* __Response__: 

L217-219: Again, please provide some detail on the spatial resolution of these datasets. Were there any issues / challenges with alignment with spatial datasets from other sources? How were these overcome?

* __Response__: Details on these data were added as follows: "The FNAI data are Florida Managed Areas as vector-based polygons of public and some private lands identified as having natural resource value and that are being managed at least partially for conservation.  The source data for this layer are provided to FNAI directly from the managing agency in digital format or as paper source maps that are digitized using appropriate topographic quadrangles, ortho-imagery, and property appraiser parcel data at a minimum spatial resolution of 1:5,000."

     A citation to @FNAI20 was also added.
     
     The common projection used for all analyses was also added to line 251: "All spatial data were transformed to the NAD83(2011) / Florida West (ftUS) projection prior to analysis."

Results:

L263-266: Could changes in seagrass also be attributed to improved ground-truthing and photointerpretation? Perhaps some additional information on the input datasets, such as how the areas were estimated, could provide some insight (as suggested to present in a table above in Methods section).

* __Response__: The change in seagrasses in Tampa Bay over the last three decades is well-documented [e.g., @Greening14; @Sherwood17].  The documentation of this recovery has been made possible primarily from efforts of the Southwest Florida Water Management District in providing accurate and comparable coverage maps on an approximate biennial basis since the late 1980s (as described in the data sources).  Although some minor changes in the FLUCCS codes have occurred during this period, the methods for documenting seagrasses have been consistent. We are confident that these changes are not a product of changes in methodologies.  We hope that our addition to the text describing more detail on the data sources and methods has provided some clarity.   

L285-295: This is valuable information, and impressive that the authors were able to collate and document the restoration projects that have been carried out across different agencies and partnerships. This information will be very important for monitoring and reporting on progress for targets going forward, so it is a critical step to have synthesized the work that has already been carried out. An additional useful output would be a spatial representation of these projects so that the map could be updated as more projects are completed in the future (but this would be beyond the scope of this paper).

* __Response__: 

L309-310: Should this read “(coastal reservation restorable)”?

* __Response__: Corrected.

L324-335: In this section describing the targets and goals, I anticipated more detail on the potential climate change effects on the habitat map. As mentioned above in a previous comment, if this has been included then please provide a clearer description of the approach. But for example, the distribution of the intertidal habitats could be different by 2050 under SLR, and therefore adjacent upland area may be lost / transitioned into intertidal habitat. The authors have mentioned landward migration and the possibility of coastal squeeze due to infrastructure in the Discussion, but I expected it to be more clearly incorporated into the Results, given the framing of the paper in the Abstract and Introduction. If this is not the case then those previous sections need to be revisited.

* __Response__: 

Discussion:

The authors have provided a suitable Discussion to contextualise the results of the paper.

Tables:

Table3: Suggest that the heading in the second column be changed to “Landcover Category” or something similar, instead of “Habitat Type” as this column includes “Developed” and “Restorable”, which would not typically be considered as habitats.

* __Response__: The column header was changed to "Landcover Category".  The table caption was also changed.

Table4: There are some discrepancies in the table, or perhaps a sentence is needed in the title to explain why the current extent is not equal to existing conservation + proposed conservation lands. For example, Mangroves current extent = 6276, existing conservation + proposed conservation = (4516+1604) = 6120. Does this indicate an additional 156 ha of mangrove that is not within a conservation area? Also, check the rounding up of the area estimates as there is a discrepancy in values presented for total restoration opportunity = existing conservation lands restoration opportunity + proposed conservation lands restoration opportunity.

* __Response__: 

Table5: This table is arguably the most important result from the paper. The only query I have is whether the authors have considered how the map would look if these targets / goals were to be achieved. For example, the target for total intertidal to increase by 61 hectares in a mosaic – how does this factor in SLR?

* __Response__: 

It is also not immediately clear from the table how the values for the 2030 targets and 2050 goals are calculated. For example, for coastal uplands if 513 ha is the total restoration opportunity, then how was 1689 ha estimated for the 2050 target (if the current extent is 1446 ha)?

* __Response__: 

If the values for the envisioned targets and goals for 2030 and 2050 are derived from the total restoration opportunity (which was estimated from the spatial data), then would it be possible to generate maps for where these locations are? Similar to Figure 5 / Figure 6?

* __Response__: 

## References 
